# Generated by Django 4.1 on 2022-08-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lives_in',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='friend',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
