# Generated by Django 4.1 on 2022-08-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='oem',
            name='notifications',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
