# Generated by Django 4.1 on 2022-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_blogpost_likes_delete_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oem',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oem',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
