# Generated by Django 4.1 on 2022-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_oem_email_oem_username_alter_oem_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('notifications', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TENDERER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('notifications', models.IntegerField(default=0)),
            ],
        ),
    ]
